language: java 
sudo: required
services:
  - docker
jdk:
  - oraclejdk8


before_script:
  - echo MAVEN_OPTS=-Xmx1536m > ~/.mavenrc

# Enable integration tests
script:
  - mvn verify -B

# Send coverage data
after_success:
  bash <(curl -s https://codecov.io/bash)

after_failure:
  - cat **/target/surefire-reports/*.xml | grep -B 1 -A 10 "<error"
  - cat **/target/failsafe-reports/*.xml | grep -B 1 -A 10 "<error"
